servers:
- udp_bind: 0.0.0.0:5053
  tcp_bind: 0.0.0.0:5053
  zone:
    type: merge
    top:
      type: postgres
      vendor: postgres
      host: localhost
      database: adns
      username: local
      password: ""
    bottom:
      type: file
      path: /runtime/zone/zone.yaml
